// Generated by CoffeeScript 1.3.3
(function() {
  var fwScraper;

  fwScraper = require("./fw_scraper.js");

  fwScraper.scrape(function(results) {
    var result, _i, _len, _results;
    console.log("framework name,# of stars,# of forks");
    _results = [];
    for (_i = 0, _len = results.length; _i < _len; _i++) {
      result = results[_i];
      _results.push(console.log("" + result.name + "," + result.starNum + "," + result.forkNum));
    }
    return _results;
  });

}).call(this);
